version: "3.7"

services:
  salt-master:
    build:
      context: .
      dockerfile: Dockerfile.master
    networks:
      my-net:
        ipv4_address: 10.0.0.200
    volumes:
      - my_vol:/etc/salt

  salt-minion:
    build:
      context: .
      dockerfile: Dockerfile.minion
    depends_on:
      - salt-master
    networks:
      my-net:
        ipv4_address: 10.0.0.201

networks:
  my-net:
    ipam:
      config:
        - subnet: 10.0.0.0/22
          gateway: 10.0.0.1

volumes:
  my_vol:
    driver: local
